//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTax.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesTax.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default to &quot;Other&quot; if pressed Enter with any other value].
        /// </summary>
        internal static string ENTER_DEFAULT {
            get {
                return ResourceManager.GetString("ENTER_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----START OF WARNING---\nThis product cannot be added to the cart due to invalid price setting. Skipping to next item...\n----END OF WARNING---.
        /// </summary>
        internal static string ERROR_INVALIDPRICE {
            get {
                return ResourceManager.GetString("ERROR_INVALIDPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax value not set. Please take a look at the configuration file..
        /// </summary>
        internal static string ERROR_TAXCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_TAXCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}.
        /// </summary>
        internal static string ITEM_COUNT_HEADER {
            get {
                return ResourceManager.GetString("ITEM_COUNT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: ${1}.
        /// </summary>
        internal static string ITEMIZE_BODY {
            get {
                return ResourceManager.GetString("ITEMIZE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} @ ${1}).
        /// </summary>
        internal static string ITEMIZE_MULTIPLE {
            get {
                return ResourceManager.GetString("ITEMIZE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax : ${0}.
        /// </summary>
        internal static string ITEMIZE_TAX {
            get {
                return ResourceManager.GetString("ITEMIZE_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price : ${0}.
        /// </summary>
        internal static string ITEMIZE_TOTAL {
            get {
                return ResourceManager.GetString("ITEMIZE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt created: {0}.
        /// </summary>
        internal static string PATH_RECEIPT {
            get {
                return ResourceManager.GetString("PATH_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process failed: {0}.
        /// </summary>
        internal static string PROCESS_FAIL {
            get {
                return ResourceManager.GetString("PROCESS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout? (Y[es]/N[o] -- must be uppercase letter).
        /// </summary>
        internal static string PROMPT_CHECKOUT {
            get {
                return ResourceManager.GetString("PROMPT_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Item (select one of below if applicable) {0}.
        /// </summary>
        internal static string PROMPT_EXEMPTED {
            get {
                return ResourceManager.GetString("PROMPT_EXEMPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this product imported? (Y[es]/N[o] -- must be an uppercase letter).
        /// </summary>
        internal static string PROMPT_IMPORTED {
            get {
                return ResourceManager.GetString("PROMPT_IMPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : .
        /// </summary>
        internal static string PROMPT_NAME {
            get {
                return ResourceManager.GetString("PROMPT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of {0}:.
        /// </summary>
        internal static string PROMPT_PRICE {
            get {
                return ResourceManager.GetString("PROMPT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected &quot;{0}&quot;.
        /// </summary>
        internal static string SELECTED_ITEM {
            get {
                return ResourceManager.GetString("SELECTED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected &quot;Other&quot;....
        /// </summary>
        internal static string SELECTED_OTHER {
            get {
                return ResourceManager.GetString("SELECTED_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction finished....
        /// </summary>
        internal static string TRANSACTIONEND {
            get {
                return ResourceManager.GetString("TRANSACTIONEND", resourceCulture);
            }
        }
    }
}
